language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  global:
    - MAVEN_OPTS="-Xmx256M"

sudo: false

cache:
  directories:
    - $HOME/.m2/io
    - $HOME/.m2/org

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -q -T 2

script: mvn test -Dair.check.skip-dependency=true
notifications:
  slack:
    secure: V5eyoGShxFoCcYJcp858vf/T6gC9KeMxL0C1EElcpZRcKBrIVZzvhek3HLHxZOxlghqnvNVsyDtU3u5orkEaAXeXj5c2dN+4XBsAB9oeN5MtQ0Z3VLAhZDqKIW1LzcXrq4DpzM0PkGhjfjum/P94/qFYk0UckPtB6a341AuYRo8=
