# Site settings
permalink: /blog/:year/:month/:day/:title/
title: Presto
tagline: A Distributed SQL Query Engine for Big Data
fbappid: ""
gacode: "UA-45503728-1"
description: >
  Presto is an open source distributed SQL query engine for running interactive analytic queries against data sources of all sizes ranging from gigabytes to petabytes. 
baseurl: 
url: https://prestodb.io
ghrepo: "facebook/presto"

# Build settings
markdown: redcarpet
highlighter: pygments

collections:
  docs:
    output: true
    permalink: /docs/:name/
  support:
    output: true
    permalink: /support/

sass:
  style: :compressed
  
gems:
  - jekyll-redirect-from

redcarpet:
  extensions: [with_toc_data, smart]

color:
  # Provides colour for background of top header of homepage
  primary: "#3a9cc4"
  # Provides colour for background of elsewhere on site
  secondary: "#fff"
  # A color that will work for buttons laid on top of primary colour
  light: "#0d4968"
  # Color that will work for text on top of light color
  lighttext: "#fff"
  # Color of text in the top header of homepage, must be legible on top of primary color
  headertext: "#fff"
  # Color of text on top of the secondary color background
  bodytext: "#393939"
  # Background of fixed nav header - headertext color is used for mini logo text
  nav: "#000000"
  # Text of links in the nav
  navtext: "#fff"
  # Color of link underlines in the main body, and hover background color for links
  link: "#48bee0"
  # Provides colour for "powered by" banner
  alternate: "#48bee0"
