version: '2'
services:
  hadoop-master:
    hostname: hadoop-master
    image: 'prestodb/hdp2.6-hive:5'
    ports:
      - '1180:1180'
      - '8020:8020'
      - '8042:8042'
      - '8088:8088'
      - '9083:9083'
      - '10000:10000'
      - '19888:19888'
      - '50070:50070'
      - '50075:50075'
    volumes:
      - ../../presto-hive/src/test/sql:/files/sql:ro
      - ./files/words:/usr/share/dict/words:ro
      - ./files/core-site.xml.s3-template:/etc/hadoop/conf/core-site.xml.s3-template:ro
      - ./files/core-site.xml.alioss-template:/etc/hadoop/conf/core-site.xml.alioss-template:ro
      - /Users/abei/.m2/repository/com/aliyun/oss/hadoop-aliyun/2.7.2/hadoop-aliyun-2.7.2.jar:/usr/hdp/2.6.3.0-235/hadoop/lib/hadoop-aliyun-2.7.2.jar
      - ./files/test1.csv:/tmp/test1.csv:ro
      - ./files/test1.csv.gz:/tmp/test1.csv.gz:ro
      - ./files/test1.csv.lz4:/tmp/test1.csv.lz4:ro
      - ./files/test1.csv.bz2:/tmp/test1.csv.bz2:ro
